services:

  # nginx
  web : 
        image : nginx:latest
        ports : 
          - "80:80"  # port 80 from local marchine map to port 80 on container
        volumes:
          # Mount my local default.conf file, replacing container default nginx config file
          - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  # php
  app : 
        build : # build custom image
          dockerfile : ./php/Dockerfile
        volumes :
          - ./app:/app


  # mysql
  db : 
        image : mysql:9.2.0

        volumes : 
          - mysqldata:/var/lib/mysql

        ports : 
          - "3306:3306"

        restart : unless-stopped

        # pass data to the db 
        environment : 
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
          MYSQL_USER: ${MYSQL_USER}
          MYSQL_PASSWORD: ${MYSQL_PASSWORD}
          MYSQL_DATABASE: ${MYSQL_DATABASE}


  # redis


# Let docker optimize the location of the data
volumes : 
  mysqldata